import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://xmnrpgdfwkxumzsjxjfd.supabase.co'
const supabaseKey = 'sb_publishable_f8GcVgk1Vn3dLGzl9amVwA_IPMcI4dj'

const supabase = createClient(supabaseUrl, supabaseKey)

const questions = 
[
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "In the XY-plane, the area, in sq. units, of the region defined by the inequalities y ≥ x + 4 and -4 ≤ x² + y² + 4(x - y) ≤ 0 is",
    "option_a": "π",
    "option_b": "2π",
    "option_c": "4π",
    "option_d": "3π",
    "correct": 1,
    "question_type": "MCQ",
    "topic": "Geometry",
    "subtopic": "Coordinate Geometry",
    "concept": "Area of region bounded by circle and line inequalities",
    "difficulty": "Hard",
    "solution": "Rewrite x² + y² + 4(x-y) ≤ 0: x² + 4x + y² - 4y ≤ 0 → (x+2)² + (y-2)² ≤ 8. This is a circle with center (-2,2) and radius 2√2. The other inequality x² + y² + 4(x-y) ≥ -4: (x+2)² + (y-2)² ≥ 4, circle with center (-2,2) and radius 2. So the region between two concentric circles (annulus). The line y = x+4 passes through center (-2,2) since 2 = -2+4 = 2. The line divides the annulus into two equal halves. We need y ≥ x+4, which is the upper-left half. Area of annulus = π(2√2)² - π(2)² = 8π - 4π = 4π. Half of this = 2π."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "The sum of all real values of k for which (1/8)^k × (1/32768)^(1/3) = (1/8) × (1/32768)^(1/k) is",
    "option_a": "4/3",
    "option_b": "-4/3",
    "option_c": "2/3",
    "option_d": "-2/3",
    "correct": 3,
    "question_type": "MCQ",
    "topic": "Algebra",
    "subtopic": "Indices and Surds",
    "concept": "Solving exponential equations",
    "difficulty": "Medium",
    "solution": "Note 1/8 = 2^(-3) and 1/32768 = 2^(-15). So: 2^(-3k) × 2^(-5) = 2^(-3) × 2^(-15/k). Thus -3k - 5 = -3 - 15/k. Rearranging: -3k - 5 + 3 + 15/k = 0 → -3k - 2 + 15/k = 0. Multiply by k: -3k² - 2k + 15 = 0 → 3k² + 2k - 15 = 0. Sum of roots = -2/3."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "The sum of all four-digit numbers that can be formed with the distinct non-zero digits a, b, c, and d, with each digit appearing exactly once in every number, is 153310 + n, where n is a single digit natural number. Then, the value of (a + b + c + d + n) is",
    "option_a": null,
    "option_b": null,
    "option_c": null,
    "option_d": null,
    "correct": null,
    "question_type": "TITA",
    "topic": "Permutation & Combination",
    "subtopic": "Number Formation",
    "concept": "Sum of all permutations of digits forming four-digit numbers",
    "difficulty": "Medium",
    "solution": "Sum of all 4-digit numbers using 4 distinct digits = (a+b+c+d) × 6 × 1111 = 6666(a+b+c+d). We're told this equals 153310 + n. So 6666(a+b+c+d) = 153310 + n. For n to be a single digit (1-9), we need 6666(a+b+c+d) between 153311 and 153319. 153310/6666 ≈ 23.00. So a+b+c+d = 23 and 6666×23 = 153318, giving n = 8. Therefore a+b+c+d+n = 23+8 = 31."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "Renu would take 15 days working 4 hours per day to complete a certain task whereas Seema would take 8 days working 5 hours per day to complete the same task. They decide to work together to complete this task. Seema agrees to work for double the number of hours per day as Renu, while Renu agrees to work for double the number of days as Seema. If Renu works 2 hours per day, then the number of days Seema will work, is",
    "option_a": null,
    "option_b": null,
    "option_c": null,
    "option_d": null,
    "correct": null,
    "question_type": "TITA",
    "topic": "Arithmetic",
    "subtopic": "Time and Work",
    "concept": "Work rate with variable hours and days",
    "difficulty": "Medium",
    "solution": "Renu's total work capacity = 15×4 = 60 person-hours. Seema's total work capacity = 8×5 = 40 person-hours. So Renu's rate = 1/60 per hour and Seema's rate = 1/40 per hour. Renu works 2 hrs/day. Seema works double = 4 hrs/day. Renu works double the days of Seema. Let Seema work d days, Renu works 2d days. Work done by Renu = 2d × 2 × (1/60) = 4d/60 = d/15. Work done by Seema = d × 4 × (1/40) = 4d/40 = d/10. Total = d/15 + d/10 = 2d/30 + 3d/30 = 5d/30 = d/6 = 1. So d = 6."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "For any natural number n, let a_n be the largest integer not exceeding √n. Then the value of a₁ + a₂ + ... + a₅₀ is",
    "option_a": null,
    "option_b": null,
    "option_c": null,
    "option_d": null,
    "correct": null,
    "question_type": "TITA",
    "topic": "Number Theory",
    "subtopic": "Floor Function",
    "concept": "Sum of floor of square roots",
    "difficulty": "Medium",
    "solution": "a_n = floor(√n). For n=1,2,3: a_n=1 (3 terms). For n=4,5,...,8: a_n=2 (5 terms). For n=9,...,15: a_n=3 (7 terms). For n=16,...,24: a_n=4 (9 terms). For n=25,...,35: a_n=5 (11 terms). For n=36,...,48: a_n=6 (13 terms). For n=49,50: a_n=7 (2 terms). Sum = 1×3 + 2×5 + 3×7 + 4×9 + 5×11 + 6×13 + 7×2 = 3 + 10 + 21 + 36 + 55 + 78 + 14 = 217."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "The surface area of a closed rectangular box, which is inscribed in a sphere, is 846 sq cm, and the sum of the lengths of all its edges is 144 cm. The volume, in cubic cm, of the sphere is",
    "option_a": "750π",
    "option_b": "1125π√2",
    "option_c": "1125π",
    "option_d": "750π√2",
    "correct": 1,
    "question_type": "MCQ",
    "topic": "Geometry",
    "subtopic": "Mensuration",
    "concept": "Rectangular box inscribed in sphere",
    "difficulty": "Hard",
    "solution": "Let dimensions be l, b, h. Sum of edges = 4(l+b+h) = 144, so l+b+h = 36. Surface area = 2(lb+bh+hl) = 846, so lb+bh+hl = 423. Diagonal of box = diameter of sphere: d² = l²+b²+h² = (l+b+h)² - 2(lb+bh+hl) = 36² - 2×423 = 1296 - 846 = 450. So d = √450 = 15√2. Radius of sphere = 15√2/2. Volume = (4/3)π(15√2/2)³ = (4/3)π × (15√2)³/8 = (4/3)π × 6750√2/8 = (4/3)π × 843.75√2 = 1125π√2."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "If x is a positive real number such that 4log₁₀x + 4log₁₀₀x + 8log₁₀₀₀x = 13, then the greatest integer not exceeding x, is",
    "option_a": null,
    "option_b": null,
    "option_c": null,
    "option_d": null,
    "correct": null,
    "question_type": "TITA",
    "topic": "Algebra",
    "subtopic": "Logarithms",
    "concept": "Converting logarithms to common base",
    "difficulty": "Medium",
    "solution": "Let log₁₀x = t. log₁₀₀x = t/2, log₁₀₀₀x = t/3. So 4t + 4(t/2) + 8(t/3) = 13 → 4t + 2t + 8t/3 = 13 → 6t + 8t/3 = 13 → 18t/3 + 8t/3 = 13 → 26t/3 = 13 → t = 3/2. So log₁₀x = 3/2, x = 10^(3/2) = 10√10 ≈ 31.62. Greatest integer not exceeding x = 31."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "If (a + b√n) is the positive square root of (29 - 12√5), where a and b are integers, and n is a natural number, then the maximum possible value of (a + b + n) is",
    "option_a": "22",
    "option_b": "4",
    "option_c": "6",
    "option_d": "18",
    "correct": 3,
    "question_type": "MCQ",
    "topic": "Algebra",
    "subtopic": "Indices and Surds",
    "concept": "Square root of surd expression",
    "difficulty": "Medium",
    "solution": "29 - 12√5 = 20 - 12√5 + 9 = (2√5)² - 2×2√5×3 + 3² = (2√5 - 3)² = (3 - 2√5)². Wait, 3 < 2√5 so this is negative. Actually (2√5-3)² = 20-12√5+9 = 29-12√5. So √(29-12√5) = 2√5-3 (since 2√5 ≈ 4.47 > 3). So a+b√n = 2√5-3, meaning a = -3, b = 2, n = 5. Thus a+b+n = -3+2+5 = 4. But we want maximum. Also could write as a+b√n where b is negative: a=2√5-3... trying other forms. If a+b√n = 2√5-3: one possibility a=-3, b=2, n=5 → sum=4. Or if we allow a=0, -3+2√5: a=-3,b=2,n=5→4. Maximum is 18: if a=3, b=-2, n=5 → but then 3-2√5 is negative. The answer key says 18. With a+b√n: if b=-2, a=3, n=5: value = 3-2√5 < 0, not valid. Trying: 29-12√5 = (a+b√n)². Expand: a²+nb² + 2ab√n = 29-12√5. So 2ab√n = -12√5 → n=5, 2ab=-12, ab=-6. And a²+5b²=29. From ab=-6: a=-6/b. Then 36/b²+5b²=29 → 5b⁴-29b²+36=0 → b²=(29±√(841-720))/10=(29±11)/10 → b²=4 or b²=9/5. So b=±2 (integer), a=∓3. Solutions: (a,b)=(3,-2) or (-3,2). a+b+n: 3+(-2)+5=6 or -3+2+5=4. But wait the question asks for maximum. Answer key says 18. Reconsidering: b can be negative integers too. With (3,-2,5): 3+(-2)+5=6. With (-3,2,5): -3+2+5=4. Maximum is 6. But answer key says 18... Let me re-examine. Actually with b negative: a=3,b=-2,n=5 gives a+b+n=6. The answer key answer is 18, which corresponds to option d. Perhaps b doesn't have to satisfy b√n = the irrational part sign-consistent. If we allow: a+b√n where we just need the VALUE to equal 2√5-3, then a=-3+2√5 has multiple representations. E.g., -3+2√5 = -3+√20, so a=-3,b=1,n=20: a+b+n=-3+1+20=18. This gives maximum 18!"
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "A shop wants to sell a certain quantity (in kg) of grains. It sells half the quantity and an additional 3 kg of these grains to the first customer. Then, it sells half of the remaining quantity and an additional 3 kg of these grains to the second customer. Finally, when the shop sells half of the remaining quantity and an additional 3 kg of these grains to the third customer, there are no grains left. The initial quantity, in kg, of grains is",
    "option_a": "50",
    "option_b": "18",
    "option_c": "42",
    "option_d": "36",
    "correct": 2,
    "question_type": "MCQ",
    "topic": "Arithmetic",
    "subtopic": "Progressions / Work backward",
    "concept": "Working backwards through sequential operations",
    "difficulty": "Easy",
    "solution": "Work backwards. After 3rd customer: 0 remaining. Before 3rd sale: let quantity be x. Sells x/2+3=x → x/2=3 → x=6. Before 2nd sale: let quantity be y. After 2nd sale: y/2-3=6 → y/2=9 → y=18. Before 1st sale: let initial = z. After 1st sale: z/2-3=18 → z/2=21 → z=42."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "Let x, y, and z be real numbers satisfying 4(x² + y² + z²) = a, 4(x - y - z) = 3 + a. Then a equals",
    "option_a": "1",
    "option_b": "3",
    "option_c": "4",
    "option_d": "1 1/3",
    "correct": 1,
    "question_type": "MCQ",
    "topic": "Algebra",
    "subtopic": "Quadratic Equations",
    "concept": "System of equations with squares",
    "difficulty": "Medium",
    "solution": "From equation 2: 4(x-y-z) = 3+a. From equation 1: 4(x²+y²+z²) = a. We need to find valid a. Note 4(x-y-z) ≤ 4√3·√(x²+y²+z²) by Cauchy-Schwarz (with coefficients 1,-1,-1). Actually 4(x-y-z)² ≤ 4·3·(x²+y²+z²) = 3a (by CS). So (3+a)²/16 ≤ 3a/4 → (3+a)² ≤ 12a → 9+6a+a² ≤ 12a → a²-6a+9 ≤ 0 → (a-3)² ≤ 0. Since (a-3)² ≥ 0, we need (a-3)² = 0, so a = 3."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "Consider two sets A = {2, 3, 5, 7, 11, 13} and B = {1, 8, 27}. Let f be a function from A to B such that for every element b in B, there is at least one element a in A such that f(a) = b. Then, the total number of such functions f is",
    "option_a": "665",
    "option_b": "667",
    "option_c": "537",
    "option_d": "540",
    "correct": 3,
    "question_type": "MCQ",
    "topic": "Permutation & Combination",
    "subtopic": "Functions and Mappings",
    "concept": "Counting surjective functions",
    "difficulty": "Hard",
    "solution": "Onto functions from A (6 elements) to B (3 elements). Using inclusion-exclusion: Total onto = 3⁶ - C(3,1)×2⁶ + C(3,2)×1⁶ = 729 - 3×64 + 3×1 = 729 - 192 + 3 = 540."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "The selling price of a product is fixed to ensure 40% profit. If the product had cost 40% less and had been sold for 5 rupees less, then the resulting profit would have been 50%. The original selling price, in rupees, of the product is",
    "option_a": "20",
    "option_b": "15",
    "option_c": "14",
    "option_d": "10",
    "correct": 0,
    "question_type": "MCQ",
    "topic": "Arithmetic",
    "subtopic": "Profit and Loss",
    "concept": "Profit percentage with changed cost and selling price",
    "difficulty": "Easy",
    "solution": "Let CP = c. SP = 1.4c. New CP = 0.6c. New SP = 1.4c - 5. New profit = 50%: (1.4c-5) = 1.5×0.6c = 0.9c. So 1.4c - 5 = 0.9c → 0.5c = 5 → c = 10. Original SP = 1.4×10 = 14. Wait, that gives 14. But answer key says a (20). Let me recheck: SP = 1.4×10 = 14. Hmm answer key says option a = 20. Let me redo: new profit 50% means profit/new_cost = 0.5, so new_SP = 1.5 × new_cost = 1.5 × 0.6c = 0.9c. New SP = original SP - 5 = 1.4c - 5. So 1.4c - 5 = 0.9c → 0.5c = 5 → c = 10, SP = 14. But answer key says (a) = 20. Re-examining: maybe 'sold for 5 rupees less' means new SP = old SP - 5, and I have that. With c=10, SP=14, option c=14. Answer key for Q12 is c. So answer is 14, option c, correct=2."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "There are four numbers such that average of first two numbers is 1 more than the first number, average of first three numbers is 2 more than average of first two numbers, and average of first four numbers is 3 more than average of first three numbers. Then, the difference between the largest and the smallest numbers, is",
    "option_a": null,
    "option_b": null,
    "option_c": null,
    "option_d": null,
    "correct": null,
    "question_type": "TITA",
    "topic": "Arithmetic",
    "subtopic": "Averages",
    "concept": "Sequential averages with conditions",
    "difficulty": "Medium",
    "solution": "Let numbers be a,b,c,d. Avg of first 2 = (a+b)/2 = a+1, so b = a+2. Avg of first 3 = (a+b+c)/3 = (a+b)/2 + 2 = a+3, so a+b+c = 3(a+3) = 3a+9. Since a+b = a+a+2 = 2a+2, c = 3a+9-(2a+2) = a+7. Avg of first 4 = (a+b+c+d)/4 = (a+b+c)/3 + 3 = a+3+3 = a+6, so a+b+c+d = 4(a+6) = 4a+24. d = 4a+24-(3a+9) = a+15. Numbers: a, a+2, a+7, a+15. Largest - smallest = (a+15) - a = 15."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "An amount of Rs 10000 is deposited in bank A for a certain number of years at a simple interest of 5% per annum. On maturity, the total amount received is deposited in bank B for another 5 years at a simple interest of 6% per annum. If the interests received from bank A and bank B are in the ratio 10:13, then the investment period, in years, in bank A is",
    "option_a": "6",
    "option_b": "4",
    "option_c": "3",
    "option_d": "5",
    "correct": 0,
    "question_type": "MCQ",
    "topic": "Arithmetic",
    "subtopic": "Simple Interest",
    "concept": "Simple interest ratio over two banks",
    "difficulty": "Easy",
    "solution": "Let years in bank A = t. Interest from A = 10000×5×t/100 = 500t. Amount at maturity = 10000 + 500t. Interest from B = (10000+500t)×6×5/100 = (10000+500t)×0.3. Ratio: 500t / [(10000+500t)×0.3] = 10/13. So 500t × 13 = 10 × 0.3 × (10000+500t). 6500t = 3(10000+500t) = 30000+1500t. 5000t = 30000. t = 6."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "A fruit seller has a total of 187 fruits consisting of apples, mangoes and oranges. The number of apples and mangoes are in the ratio 5:2. After she sells 75 apples, 26 mangoes and half of the oranges, the ratio of number of unsold apples to number of unsold oranges becomes 3:2. The total number of unsold fruits is",
    "option_a": null,
    "option_b": null,
    "option_c": null,
    "option_d": null,
    "correct": null,
    "question_type": "TITA",
    "topic": "Arithmetic",
    "subtopic": "Ratio and Proportion",
    "concept": "Ratio problems with fruits",
    "difficulty": "Easy",
    "solution": "Apples:Mangoes = 5:2. Let apples=5k, mangoes=2k. 5k+2k+oranges=187 → oranges=187-7k. After selling: apples left = 5k-75, oranges left = (187-7k)/2. Ratio (5k-75)/[(187-7k)/2] = 3/2. So 2(5k-75) = 3(187-7k)/2... actually: (5k-75)/[(187-7k)/2] = 3/2 → 2(5k-75)×2 = 3(187-7k) → 4(5k-75) = 3(187-7k) → 20k-300 = 561-21k → 41k = 861 → k=21. Apples=105, mangoes=42, oranges=40. After selling: apples=30, mangoes=16, oranges=20. Total unsold = 30+16+20 = 66."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "ABCD is a rectangle with sides AB = 56 cm and BC = 45 cm, and E is the midpoint of side CD. Then, the length, in cm, of radius of incircle of △ADE is",
    "option_a": null,
    "option_b": null,
    "option_c": null,
    "option_d": null,
    "correct": null,
    "question_type": "TITA",
    "topic": "Geometry",
    "subtopic": "Triangles",
    "concept": "Incircle radius of a triangle",
    "difficulty": "Medium",
    "solution": "AB=56, BC=45. So AD=BC=45, CD=AB=56. E is midpoint of CD, so DE=28. In triangle ADE: AD=45, DE=28, AE=? AE²=AD²+DE²... wait, A is a corner. Let A=(0,45), D=(0,0), E=(28,0). AD=45, DE=28. AE=√(28²+45²)=√(784+2025)=√2809=53. Triangle ADE has sides AD=45, DE=28, AE=53. Semi-perimeter s=(45+28+53)/2=126/2=63. Area = (1/2)×28×45=630. Inradius r = Area/s = 630/63 = 10."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "If the equations x² + mx + 9 = 0, x² + nx + 17 = 0 and x² + (m+n)x + 35 = 0 have a common negative root, then the value of (2m + 3n) is",
    "option_a": null,
    "option_b": null,
    "option_c": null,
    "option_d": null,
    "correct": null,
    "question_type": "TITA",
    "topic": "Algebra",
    "subtopic": "Quadratic Equations",
    "concept": "Common roots of quadratic equations",
    "difficulty": "Hard",
    "solution": "Let common negative root be -r (r>0). From eq1: r²-mr+9=0. From eq2: r²-nr+17=0. From eq3: r²-(m+n)r+35=0. Note eq3 = eq1 + eq2 - r²... actually (r²-mr+9)+(r²-nr+17)=r²-(m+n)r+35 +r². So 2r²-(m+n)r+26 = r²-(m+n)r+35+r² → 26=35, contradiction. So the common root must be common across specific pairs. Let -r be common to all three. From eq1-eq2: (m-n)(-r)=9-17=-8... wait: subtracting eq2 from eq1: (m-n)x+(9-17)=0 → x=8/(m-n). From eq1-eq3: -nx+(9-35)=0... Subtracting eq1 from eq3: (m+n-m)x+35-9=0 → nx+26=0 → x=-26/n. Subtracting eq2 from eq3: mx+18=0 → x=-18/m. Common root: -r = 8/(m-n) = -26/n = -18/m. From -26/n = -18/m: 26m=18n → 13m=9n. From -18/m = r and -26/n = r: m=18/r, n=26/r. 13(18/r)=9(26/r) → 234=234 ✓. Using eq1: r²-mr+9=0 → r²-(18/r)r+9=0 → r²-18+9=0 → r²=9 → r=3. So m=6, n=26/3... hmm not integer. Let me use product of roots. For eq1: product of roots=9, for common root -r, other root = -9/r. For eq2: other root = -17/r. For eq3: other root = -35/r. Eq3 roots are common root (-r) and another. Sum of roots eq3: -r + (-35/r) = -(m+n). Also -r+(-9/r)=-m and -r+(-17/r)=-n. So m=r+9/r, n=r+17/r, m+n=2r+26/r. And from eq3 sum: r+35/r=m+n=2r+26/r → 35/r-26/r=r → 9/r=r → r²=9 → r=3. m=3+3=6, n=3+17/3=26/3... Still non-integer. But 2m+3n=12+26=38. Let me check: 2(6)+3(26/3)=12+26=38."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "In September, the incomes of Kamal, Amal and Vimal are in the ratio 8:6:5. They rent a house together, and Kamal pays 15%, Amal pays 12% and Vimal pays 18% of their respective incomes to cover the total house rent in that month. In October, the house rent remains unchanged while their incomes increase by 10%, 12% and 15%, respectively. In October, the percentage of their total income that will be paid as house rent, is nearest to",
    "option_a": "15.18",
    "option_b": "13.26",
    "option_c": "12.75",
    "option_d": "14.84",
    "correct": 1,
    "question_type": "MCQ",
    "topic": "Arithmetic",
    "subtopic": "Percentages",
    "concept": "Percentage of income as rent after income changes",
    "difficulty": "Medium",
    "solution": "Let incomes be 8k, 6k, 5k. September rent = 0.15×8k + 0.12×6k + 0.18×5k = 1.2k+0.72k+0.9k = 2.82k. Total September income = 19k. October incomes: 8k×1.1=8.8k, 6k×1.12=6.72k, 5k×1.15=5.75k. Total October income = 21.27k. Rent unchanged = 2.82k. Percentage = 2.82/21.27 × 100 ≈ 13.26%."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "Suppose x₁, x₂, x₃, ..., x₁₀₀ are in arithmetic progression such that x₅ = -4 and 2x₆ + 2x₉ = x₁₁ + x₁₃. Then, x₁₀₀ equals",
    "option_a": "-196",
    "option_b": "206",
    "option_c": "204",
    "option_d": "-194",
    "correct": 3,
    "question_type": "MCQ",
    "topic": "Algebra",
    "subtopic": "Arithmetic Progressions",
    "concept": "Finding terms of AP with given conditions",
    "difficulty": "Medium",
    "solution": "Let first term = a, common difference = d. x₅ = a+4d = -4. 2x₆+2x₉ = x₁₁+x₁₃: 2(a+5d)+2(a+8d) = (a+10d)+(a+12d). 2a+10d+2a+16d = 2a+22d. 4a+26d = 2a+22d. 2a+4d=0 → a+2d=0 → a=-2d. From a+4d=-4: -2d+4d=-4 → 2d=-4 → d=-2. a=4. x₁₀₀ = a+99d = 4+99×(-2) = 4-198 = -194."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "A glass is filled with milk. Two-thirds of its content is poured out and replaced with water. If this process of pouring out two-thirds the content and replacing with water is repeated three more times, then the final ratio of milk to water in the glass, is",
    "option_a": "1:26",
    "option_b": "1:80",
    "option_c": "1:27",
    "option_d": "1:81",
    "correct": 1,
    "question_type": "MCQ",
    "topic": "Arithmetic",
    "subtopic": "Mixtures and Alligations",
    "concept": "Repeated dilution of mixture",
    "difficulty": "Easy",
    "solution": "Each time 2/3 is poured out, 1/3 of current milk remains. Process is done 4 times total (once + 3 more). Milk fraction = (1/3)⁴ = 1/81. Water fraction = 80/81. Ratio milk:water = 1:80."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "Two places A and B are 45 kms apart and connected by a straight road. Anil goes from A to B while Sunil goes from B to A. Starting at the same time, they cross each other in exactly 1 hour 30 minutes. If Anil reaches B exactly 1 hour 15 minutes after Sunil reaches A, the speed of Anil, in km per hour, is",
    "option_a": "18",
    "option_b": "14",
    "option_c": "12",
    "option_d": "16",
    "correct": 2,
    "question_type": "MCQ",
    "topic": "Arithmetic",
    "subtopic": "Time, Speed and Distance",
    "concept": "Relative speed and meeting point",
    "difficulty": "Medium",
    "solution": "Let Anil's speed = a, Sunil's speed = s. They meet after 1.5 hrs: 1.5(a+s)=45 → a+s=30. Time for Anil to reach B = 45/a. Time for Sunil to reach A = 45/s. Given 45/a - 45/s = 1.25 (Anil is slower). From a+s=30: s=30-a. 45/a - 45/(30-a) = 5/4. 45(30-a-a)/[a(30-a)] = 5/4. 45(30-2a) = 5a(30-a)/4. 36(30-2a) = a(30-a). 1080-72a = 30a-a². a²-102a+1080=0. a=(102±√(10404-4320))/2=(102±√6084)/2=(102±78)/2. a=90 or a=12. Since a+s=30, a=12, s=18."
  },
  {
    "year": 2024,
    "slot": 1,
    "exam": "CAT",
    "section": "QA",
    "question_text": "When 10^100 is divided by 7, the remainder is",
    "option_a": "1",
    "option_b": "3",
    "option_c": "4",
    "option_d": "6",
    "correct": 2,
    "question_type": "MCQ",
    "topic": "Number Theory",
    "subtopic": "Remainders",
    "concept": "Cyclicity of remainders with powers of 10",
    "difficulty": "Easy",
    "solution": "10 ≡ 3 (mod 7). Powers of 3 mod 7: 3¹=3, 3²=2, 3³=6, 3⁴=4, 3⁵=5, 3⁶=1, cycle length 6. 100 = 16×6+4. So 3^100 ≡ 3⁴ = 81 ≡ 4 (mod 7). Therefore 10^100 ≡ 4 (mod 7)."
  }
]

async function insertQuestions() {
  const { data, error } = await supabase
    .from('questions')
    .insert(questions)

  if (error) {
    console.error('Error inserting:', error)
  } else {
    console.log('Successfully inserted', questions.length, 'questions')
  }
}

insertQuestions()